"""changed column date created to use date method

Revision ID: 39626ce70167
Revises: ab8eb1bee08c
Create Date: 2023-08-11 14:41:56.985342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39626ce70167'
down_revision = 'ab8eb1bee08c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('date_created',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('date_created',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
